### ISSUE TITLE
 Development Strategy

### ISSUE THREAD

**Issue by SWAPNACHEMBOTH** [lab-brussels-1/HYF-redesign-group-2#17]
- [ ] Create a new branch 'development strategy'
- [ ] Assign yourself
- [ ] Add labels,milestones and project
- [ ] Complete 'development-strategy.md'

**Comment by hadoan149** [comment]
hey @SWAPNACHEMBOTH , you don't need to create an issue for PR :)

**Comment by SWAPNACHEMBOTH** [comment]
@hadoan149 ,thank you...It was edited
